# Generated by Django 5.0.4 on 2024-09-18 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_alter_userwishlist_wishlist_registration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userwishlist',
            name='wishlist_user',
        ),
    ]
