# Generated by Django 5.0.4 on 2024-09-18 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0004_userwishlist_wishlist_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userwishlist',
            name='wishlist_user',
        ),
    ]
