# Generated by Django 5.0.4 on 2024-08-30 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('gender', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('time_of_birth', models.TimeField()),
                ('place_of_birth', models.CharField(max_length=100)),
                ('mother_tongue', models.CharField(max_length=50)),
                ('marital_status', models.CharField(max_length=20)),
                ('father_name', models.CharField(max_length=100)),
                ('father_occupation', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('mother_occupation', models.CharField(max_length=100)),
                ('no_of_brothers', models.PositiveIntegerField()),
                ('no_of_married_brothers', models.PositiveIntegerField()),
                ('no_of_sisters', models.PositiveIntegerField()),
                ('no_of_married_sisters', models.PositiveIntegerField()),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('physical_status', models.CharField(max_length=50)),
                ('body_type', models.CharField(max_length=50)),
                ('complexion', models.CharField(max_length=50)),
                ('diet', models.CharField(max_length=50)),
                ('educational_qualification', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=100)),
                ('place_of_job', models.CharField(max_length=100)),
                ('income_per_month', models.DecimalField(decimal_places=2, max_digits=10)),
                ('religious', models.CharField(max_length=100)),
                ('caste', models.CharField(max_length=100)),
                ('gothra', models.CharField(max_length=100)),
                ('lagnam', models.CharField(max_length=100)),
                ('raasi', models.CharField(max_length=100)),
                ('star', models.CharField(max_length=100)),
                ('dosha', models.CharField(max_length=100)),
                ('raasi_chart', models.ImageField(blank=True, null=True, upload_to='raasi_chart/')),
                ('navamsam_chart', models.ImageField(blank=True, null=True, upload_to='navamsam_chart/')),
                ('contact_name', models.CharField(max_length=120)),
                ('mobileNumber', models.CharField(max_length=120)),
                ('whatsapp', models.CharField(max_length=20)),
                ('country', models.CharField(default='india', max_length=120)),
                ('state', models.CharField(max_length=120)),
                ('district', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=120)),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('photo4', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('preference_religion', models.CharField(max_length=100)),
                ('preference_caste', models.CharField(max_length=100)),
                ('preference_marital_status', models.CharField(max_length=20)),
                ('preference_diet', models.CharField(max_length=50)),
                ('preference_educational_qualification', models.CharField(max_length=100)),
                ('preference_job', models.CharField(max_length=100)),
                ('preference_income_per_month', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preference_location', models.CharField(max_length=120)),
            ],
        ),
    ]
